/*
 * File: IMUParser.cpp
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Tue Apr 30 11:49:11 2024
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                IMUParser

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     3

/* Input Port  0 */
#define IN_PORT_0_NAME                 u0
#define INPUT_0_DIMS_ND                {24,1}
#define INPUT_0_NUM_ELEMS              24
#define INPUT_0_WIDTH                  24
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  uint8_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define INPUT_0_UNIT                   ""
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  0
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            9
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 mem
#define INPUT_1_DIMS_ND                {16,1}
#define INPUT_1_NUM_ELEMS              16
#define INPUT_1_WIDTH                  16
#define INPUT_DIMS_1_COL               1
#define INPUT_1_DTYPE                  real_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define INPUT_1_UNIT                   ""
#define IN_1_BUS_BASED                 0
#define IN_1_BUS_NAME
#define IN_1_DIMS                      1-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  0
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            9
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125

/* Input Port  2 */
#define IN_PORT_2_NAME                 buffin
#define INPUT_2_DIMS_ND                {1000,1}
#define INPUT_2_NUM_ELEMS              1000
#define INPUT_2_WIDTH                  1000
#define INPUT_DIMS_2_COL               1
#define INPUT_2_DTYPE                  uint8_T
#define INPUT_2_COMPLEX                COMPLEX_NO
#define INPUT_2_UNIT                   ""
#define IN_2_BUS_BASED                 0
#define IN_2_BUS_NAME
#define IN_2_DIMS                      1-D
#define INPUT_2_FEEDTHROUGH            1
#define IN_2_ISSIGNED                  0
#define IN_2_WORDLENGTH                8
#define IN_2_FIXPOINTSCALING           1
#define IN_2_FRACTIONLENGTH            9
#define IN_2_BIAS                      0
#define IN_2_SLOPE                     0.125
#define NUM_OUTPUTS                    8

/* Output Port  0 */
#define OUT_PORT_0_NAME                samp
#define OUTPUT_0_DIMS_ND               {1,1}
#define OUTPUT_0_NUM_ELEMS             1
#define OUTPUT_0_WIDTH                 1
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUTPUT_0_UNIT                  ""
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     1-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                theta
#define OUTPUT_1_DIMS_ND               {3,1}
#define OUTPUT_1_NUM_ELEMS             3
#define OUTPUT_1_WIDTH                 3
#define OUTPUT_DIMS_1_COL              1
#define OUTPUT_1_DTYPE                 real_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUTPUT_1_UNIT                  ""
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     1-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125

/* Output Port  2 */
#define OUT_PORT_2_NAME                omega
#define OUTPUT_2_DIMS_ND               {3,1}
#define OUTPUT_2_NUM_ELEMS             3
#define OUTPUT_2_WIDTH                 3
#define OUTPUT_DIMS_2_COL              1
#define OUTPUT_2_DTYPE                 real_T
#define OUTPUT_2_COMPLEX               COMPLEX_NO
#define OUTPUT_2_UNIT                  ""
#define OUT_2_BUS_BASED                0
#define OUT_2_BUS_NAME
#define OUT_2_DIMS                     1-D
#define OUT_2_ISSIGNED                 1
#define OUT_2_WORDLENGTH               8
#define OUT_2_FIXPOINTSCALING          1
#define OUT_2_FRACTIONLENGTH           3
#define OUT_2_BIAS                     0
#define OUT_2_SLOPE                    0.125

/* Output Port  3 */
#define OUT_PORT_3_NAME                acc
#define OUTPUT_3_DIMS_ND               {3,1}
#define OUTPUT_3_NUM_ELEMS             3
#define OUTPUT_3_WIDTH                 3
#define OUTPUT_DIMS_3_COL              1
#define OUTPUT_3_DTYPE                 real_T
#define OUTPUT_3_COMPLEX               COMPLEX_NO
#define OUTPUT_3_UNIT                  ""
#define OUT_3_BUS_BASED                0
#define OUT_3_BUS_NAME
#define OUT_3_DIMS                     1-D
#define OUT_3_ISSIGNED                 1
#define OUT_3_WORDLENGTH               8
#define OUT_3_FIXPOINTSCALING          1
#define OUT_3_FRACTIONLENGTH           3
#define OUT_3_BIAS                     0
#define OUT_3_SLOPE                    0.125

/* Output Port  4 */
#define OUT_PORT_4_NAME                IMUtemp
#define OUTPUT_4_DIMS_ND               {1,1}
#define OUTPUT_4_NUM_ELEMS             1
#define OUTPUT_4_WIDTH                 1
#define OUTPUT_DIMS_4_COL              1
#define OUTPUT_4_DTYPE                 real_T
#define OUTPUT_4_COMPLEX               COMPLEX_NO
#define OUTPUT_4_UNIT                  ""
#define OUT_4_BUS_BASED                0
#define OUT_4_BUS_NAME
#define OUT_4_DIMS                     1-D
#define OUT_4_ISSIGNED                 1
#define OUT_4_WORDLENGTH               8
#define OUT_4_FIXPOINTSCALING          1
#define OUT_4_FRACTIONLENGTH           3
#define OUT_4_BIAS                     0
#define OUT_4_SLOPE                    0.125

/* Output Port  5 */
#define OUT_PORT_5_NAME                RcvAck
#define OUTPUT_5_DIMS_ND               {1,1}
#define OUTPUT_5_NUM_ELEMS             1
#define OUTPUT_5_WIDTH                 1
#define OUTPUT_DIMS_5_COL              1
#define OUTPUT_5_DTYPE                 uint8_T
#define OUTPUT_5_COMPLEX               COMPLEX_NO
#define OUTPUT_5_UNIT                  ""
#define OUT_5_BUS_BASED                0
#define OUT_5_BUS_NAME
#define OUT_5_DIMS                     1-D
#define OUT_5_ISSIGNED                 1
#define OUT_5_WORDLENGTH               8
#define OUT_5_FIXPOINTSCALING          1
#define OUT_5_FRACTIONLENGTH           3
#define OUT_5_BIAS                     0
#define OUT_5_SLOPE                    0.125

/* Output Port  6 */
#define OUT_PORT_6_NAME                memout
#define OUTPUT_6_DIMS_ND               {16,1}
#define OUTPUT_6_NUM_ELEMS             16
#define OUTPUT_6_WIDTH                 16
#define OUTPUT_DIMS_6_COL              1
#define OUTPUT_6_DTYPE                 real_T
#define OUTPUT_6_COMPLEX               COMPLEX_NO
#define OUTPUT_6_UNIT                  ""
#define OUT_6_BUS_BASED                0
#define OUT_6_BUS_NAME
#define OUT_6_DIMS                     1-D
#define OUT_6_ISSIGNED                 1
#define OUT_6_WORDLENGTH               8
#define OUT_6_FIXPOINTSCALING          1
#define OUT_6_FRACTIONLENGTH           3
#define OUT_6_BIAS                     0
#define OUT_6_SLOPE                    0.125

/* Output Port  7 */
#define OUT_PORT_7_NAME                buffer
#define OUTPUT_7_DIMS_ND               {1000,1}
#define OUTPUT_7_NUM_ELEMS             1000
#define OUTPUT_7_WIDTH                 1000
#define OUTPUT_DIMS_7_COL              1
#define OUTPUT_7_DTYPE                 uint8_T
#define OUTPUT_7_COMPLEX               COMPLEX_NO
#define OUTPUT_7_UNIT                  ""
#define OUT_7_BUS_BASED                0
#define OUT_7_BUS_NAME
#define OUT_7_DIMS                     1-D
#define OUT_7_ISSIGNED                 1
#define OUT_7_WORDLENGTH               8
#define OUT_7_FIXPOINTSCALING          1
#define OUT_7_FRACTIONLENGTH           3
#define OUT_7_BIAS                     0
#define OUT_7_SLOPE                    0.125
#define NPARAMS                        0
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           1
#define SOURCEFILES                    "__SFB__"
#define PANELINDEX                     0
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             1
#define CREATE_DEBUG_MEXFILE           1
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

extern void IMUParser_Outputs_wrapper(const uint8_T *u0,
  const real_T *mem,
  const uint8_T *buffin,
  real_T *samp,
  real_T *theta,
  real_T *omega,
  real_T *acc,
  real_T *IMUtemp,
  uint8_T *RcvAck,
  real_T *memout,
  uint8_T *buffer);

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  ssSetNumSFcnParams(S, NPARAMS);
  if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);
  ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssSetInputPortWidth(S, 0, INPUT_0_NUM_ELEMS);
  ssSetInputPortDataType(S, 0, SS_UINT8);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /* Input Port 1 */
  ssSetInputPortWidth(S, 1, INPUT_1_NUM_ELEMS);
  ssSetInputPortDataType(S, 1, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/

  /* Input Port 2 */
  ssSetInputPortWidth(S, 2, INPUT_2_NUM_ELEMS);
  ssSetInputPortDataType(S, 2, SS_UINT8);
  ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 2, 1);/*direct input signal access*/

  /*
   * Configure the Units for Input Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId inUnitIdReg;
    ssRegisterUnitFromExpr(S, INPUT_0_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 0, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port u0 of S-Function IMUParser");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_1_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 1, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port mem of S-Function IMUParser");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_2_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 2, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port buffin of S-Function IMUParser");
      return;
    }

#endif

  }

  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  ssSetOutputPortWidth(S, 0, OUTPUT_0_NUM_ELEMS);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /* Output Port 1 */
  ssSetOutputPortWidth(S, 1, OUTPUT_1_NUM_ELEMS);
  ssSetOutputPortDataType(S, 1, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

  /* Output Port 2 */
  ssSetOutputPortWidth(S, 2, OUTPUT_2_NUM_ELEMS);
  ssSetOutputPortDataType(S, 2, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);

  /* Output Port 3 */
  ssSetOutputPortWidth(S, 3, OUTPUT_3_NUM_ELEMS);
  ssSetOutputPortDataType(S, 3, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);

  /* Output Port 4 */
  ssSetOutputPortWidth(S, 4, OUTPUT_4_NUM_ELEMS);
  ssSetOutputPortDataType(S, 4, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);

  /* Output Port 5 */
  ssSetOutputPortWidth(S, 5, OUTPUT_5_NUM_ELEMS);
  ssSetOutputPortDataType(S, 5, SS_UINT8);
  ssSetOutputPortComplexSignal(S, 5, OUTPUT_5_COMPLEX);

  /* Output Port 6 */
  ssSetOutputPortWidth(S, 6, OUTPUT_6_NUM_ELEMS);
  ssSetOutputPortDataType(S, 6, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 6, OUTPUT_6_COMPLEX);

  /* Output Port 7 */
  ssSetOutputPortWidth(S, 7, OUTPUT_7_NUM_ELEMS);
  ssSetOutputPortDataType(S, 7, SS_UINT8);
  ssSetOutputPortComplexSignal(S, 7, OUTPUT_7_COMPLEX);

  /*
   * Configure the Units for Output Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId outUnitIdReg;
    ssRegisterUnitFromExpr(S, OUTPUT_0_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 0, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port samp of S-Function IMUParser");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_1_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 1, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port theta of S-Function IMUParser");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_2_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 2, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port omega of S-Function IMUParser");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_3_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 3, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port acc of S-Function IMUParser");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_4_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 4, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port IMUtemp of S-Function IMUParser");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_5_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 5, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port RcvAck of S-Function IMUParser");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_6_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 6, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port memout of S-Function IMUParser");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_7_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 7, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port buffer of S-Function IMUParser");
      return;
    }

#endif

  }

  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "24.1");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetRuntimeThreadSafetyCompliance(S, RUNTIME_THREAD_SAFETY_COMPLIANCE_FALSE);
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_DEFAULT_PORT_DIMENSION_INFO

static void mdlSetDefaultPortDimensionInfo(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(portDimsInfo);
  int_T dims[2];

  /* Setting default dimensions for input port 0 */
  portDimsInfo.width = INPUT_0_NUM_ELEMS;
  dims[0] = INPUT_0_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.dims = dims;
  portDimsInfo.numDims = 2;
  if (ssGetInputPortWidth(S, 0) == DYNAMICALLY_SIZED) {
    ssSetInputPortMatrixDimensions(S, 0, 1 , 1);
  }

  /* Setting default dimensions for input port 1 */
  portDimsInfo.width = INPUT_1_NUM_ELEMS;
  dims[0] = INPUT_1_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.dims = dims;
  portDimsInfo.numDims = 2;
  if (ssGetInputPortWidth(S, 1) == DYNAMICALLY_SIZED) {
    ssSetInputPortMatrixDimensions(S, 1, 1 , 1);
  }

  /* Setting default dimensions for input port 2 */
  portDimsInfo.width = INPUT_2_NUM_ELEMS;
  dims[0] = INPUT_2_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.dims = dims;
  portDimsInfo.numDims = 2;
  if (ssGetInputPortWidth(S, 2) == DYNAMICALLY_SIZED) {
    ssSetInputPortMatrixDimensions(S, 2, 1 , 1);
  }

  /* Setting default dimensions for output port 1 */
  portDimsInfo.width = OUTPUT_1_NUM_ELEMS;
  dims[0] = OUTPUT_1_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 1) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 1, &portDimsInfo);
  }

  /* Setting default dimensions for output port 2 */
  portDimsInfo.width = OUTPUT_2_NUM_ELEMS;
  dims[0] = OUTPUT_2_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 2) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 2, &portDimsInfo);
  }

  /* Setting default dimensions for output port 3 */
  portDimsInfo.width = OUTPUT_3_NUM_ELEMS;
  dims[0] = OUTPUT_3_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 3) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 3, &portDimsInfo);
  }

  /* Setting default dimensions for output port 6 */
  portDimsInfo.width = OUTPUT_6_NUM_ELEMS;
  dims[0] = OUTPUT_6_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 6) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 6, &portDimsInfo);
  }

  /* Setting default dimensions for output port 7 */
  portDimsInfo.width = OUTPUT_7_NUM_ELEMS;
  dims[0] = OUTPUT_7_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 7) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 7, &portDimsInfo);
  }

  return;
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const uint8_T *u0 = (uint8_T *) ssGetInputPortRealSignal(S, 0);
  const real_T *mem = (real_T *) ssGetInputPortRealSignal(S, 1);
  const uint8_T *buffin = (uint8_T *) ssGetInputPortRealSignal(S, 2);
  real_T *samp = (real_T *) ssGetOutputPortRealSignal(S, 0);
  real_T *theta = (real_T *) ssGetOutputPortRealSignal(S, 1);
  real_T *omega = (real_T *) ssGetOutputPortRealSignal(S, 2);
  real_T *acc = (real_T *) ssGetOutputPortRealSignal(S, 3);
  real_T *IMUtemp = (real_T *) ssGetOutputPortRealSignal(S, 4);
  uint8_T *RcvAck = (uint8_T *) ssGetOutputPortRealSignal(S, 5);
  real_T *memout = (real_T *) ssGetOutputPortRealSignal(S, 6);
  uint8_T *buffer = (uint8_T *) ssGetOutputPortRealSignal(S, 7);
  IMUParser_Outputs_wrapper(u0, mem, buffin, samp, theta, omega, acc, IMUtemp,
    RcvAck, memout, buffer);
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
